### ISSUE TITLE
Bug: Subscription Renewal Fails When Order Not Present

### ISSUE THREAD

**Issue by jessehanley** [bentonow/bento-wordpress-sdk#19]
![image](https://github.com/bentonow/bento-wordpress-sdk/assets/6285267/5dbfdc8f-d9e2-4e1c-8dd6-a2c7c113d89f)

"Looking at the subscription in question, the Parent order was empty as this was a subscription that I manually created in the admin. It's 4am here so I'm turning in, but I'll check back tomorrow if you need any other detail. I manually created the renewal and paid for it so it's not urgent on my end." — from Isaac at Sprucely. 

@joedawson looks like subscription renewals fail if they don't have an associated $order ... perhaps we just skip adding the unique key if the order doesn't exist? Whatchya think? 

![image](https://github.com/bentonow/bento-wordpress-sdk/assets/6285267/2a9097b0-dd2d-434f-99a2-ca41b1c67a05)

**Comment by sisaacrussell** [comment]
I also was able to trigger this fatal by simply creating a subscription manually in the admin without a parent order.
