### ISSUE TITLE
LearnDash Integration

### ISSUE THREAD

**Issue by codemonkey-jack** [bentonow/bento-wordpress-sdk#8]
Placeholder ticket for LearnDash integration for Bento. 

- [ ] Setup initial integration
- [ ] Send Events
- [ ] Course Complete
- [ ] Course Incomplete
- [ ] Lesson Complete
- [ ] Lesson Incomplete
- [ ] Topic Complete
- [ ] Topic Incomplete
- [ ] Quiz Complete
- [ ] Quiz Incomplete
- [ ] New Drip Content available (per post type)
- [ ] User not logged in X days
- [ ] User not completed a lesson in X days
- [ ] User earns a new certificate
- [ ] Users assignment has been graded
- [ ] Users essay has been graded 
- [ ] Users assignment has a new comment
- [ ] User enrolls in a course
- [ ] User enrolls in a group
- [ ] Users buys a course
- [ ] User buys a group
- [ ] TBC

**Comment by jessehanley** [comment]
Hey @codemonkey-jack! 

**Thank you so much for kicking this off 🥳** 

This sounds like a wonderful list of events to send into Bento from LearnDash! Pumped!

Quick TLDR of our event system/API used in this library: **events** are the heartbeat of Bento. The current WordPress SDK just uses a private JSON endpoint that takes in an event with a `type` (event name), `site` (your public site which is saved in settings), `email`, `details` (stuff that can be filtered on in a Workflow like a course name), and `fields` (stuff that is merged to a visitor like first_name and last_name — things you may segment on). 

Both details and fields are hashes (shown below).

An example of a simple CURL request that will pipe an event into the system: 

```curl -X POST -H "Content-Type: application/json" -d '{"site":"REPLACE ME", "email": "test@test.com", "type":"QuizComplete", "details": {"quiz_name": "test"}, "fields": {"first_name": "Jesse"}}' https://app.bentonow.com/tracking/generic```

Then in Workflows you will be able to filter by all of this magic!

**Comment by RoseAmS** [comment]
Hi @jessehanley!
Just adding some events:

- [ ] Essay submitted
- [ ] Quiz Failed
- [ ] Quiz Score - _could be saved in a custom field_

**Comment by jessehanley** [comment]
Nice ones @RoseAmS! I think trying to work out what is best stored as a `field` may need some discussion. Stuff like `course_completed_count` etc would be fun to haves. Because I'm not a LD customer, will take inspiration from you and @codemonkey-jack :)

**Comment by avdi** [comment]
I do a lot of beta and/or living courses, to which I regularly add new topics. The thing I've always wanted is an easy way to let everyone enrolled in Course X know that a new lesson/topic has been added. Including the new content's post type, title, excerpt, etc.
